import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import esbuildSvelte from 'esbuild-svelte';
import { sveltePreprocess } from 'svelte-preprocess';
import { mkdirSync } from 'node:fs';

// 关键路径:产物统一放 dist/ 下,避免污染仓库根。
// 开发期和发布期的 main.js / worker.js 都从 dist/ 读。
mkdirSync('dist', { recursive: true });

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Main plugin bundle
const mainContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	// 关键路径:vectra 等 node-only 依赖使用 `node:fs` / `node:path` 协议,
	// 必须在 `platform: 'node'` 下 esbuild 才识别。
	platform: 'node',
	// 关键路径:`onnxruntime-node` 包含 `.node` native 二进制,
	// esbuild 不会打,需留到运行时 require。
	external: [
		'obsidian',
		'electron',
		'onnxruntime-node',
		'@huggingface/transformers',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'dist/main.js',
	minify: prod,
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: 'injected' },
			preprocess: sveltePreprocess(),
		}),
	],
});

// Worker bundle (separate entry point)
const workerContext = await esbuild.context({
	entryPoints: ['src/worker/index.ts'],
	bundle: true,
	// 关键路径:Worker 也是 node 环境,vectra 同样依赖 node:fs / node:path。
	platform: 'node',
	// 关键路径:同上,Worker 不做 ONNX 推理,但 vectra 仍需 external。
	external: [
		'obsidian',
		'electron',
		'onnxruntime-node',
		'@huggingface/transformers',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'dist/worker.js',
	minify: prod,
});

if (prod) {
	await mainContext.rebuild();
	await workerContext.rebuild();
	process.exit(0);
} else {
	await mainContext.watch();
	await workerContext.watch();
}
